services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - pesquisa
    links:
      - pesquisa
    networks:
      backend:
        ipv4_address: 172.16.238.8

  database:
    image: postgres:16.4
    networks:
      backend:
        ipv4_address: 172.16.238.10
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "timezone=America/Sao_Paulo"]

  pesquisa:
    image: pesquisa
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8002:8002"
    networks:
      backend:
        ipv4_address: 172.16.238.11
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@172.16.238.10:5432/app_db

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

volumes:
  pgdata: