"""atualiza tabelas pesquisa

Revision ID: 0cdd6dc96363
Revises: 43dcd952149d
Create Date: 2024-10-13 11:41:29.371628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdd6dc96363'
down_revision: Union[str, None] = '43dcd952149d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionarios_id'), 'questionarios', ['id'], unique=False)
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('TEXT', 'SELECT_SINGLE', 'SELECT_MULTIPLE', name='tipoquestao'), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.Column('limite_respostas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questoes_id'), 'questoes', ['id'], unique=False)
    op.create_table('respostas_questionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respostas_questionario_id'), 'respostas_questionario', ['id'], unique=False)
    op.create_table('opcoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opcoes_id'), 'opcoes', ['id'], unique=False)
    op.create_table('respostas_questao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resposta_questionario_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('resposta_texto', sa.Text(), nullable=True),
    sa.Column('opcao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opcao_id'], ['opcoes.id'], ),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.ForeignKeyConstraint(['resposta_questionario_id'], ['respostas_questionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respostas_questao_id'), 'respostas_questao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_respostas_questao_id'), table_name='respostas_questao')
    op.drop_table('respostas_questao')
    op.drop_index(op.f('ix_opcoes_id'), table_name='opcoes')
    op.drop_table('opcoes')
    op.drop_index(op.f('ix_respostas_questionario_id'), table_name='respostas_questionario')
    op.drop_table('respostas_questionario')
    op.drop_index(op.f('ix_questoes_id'), table_name='questoes')
    op.drop_table('questoes')
    op.drop_index(op.f('ix_questionarios_id'), table_name='questionarios')
    op.drop_table('questionarios')
    # ### end Alembic commands ###
