"""atualiza tabelas pesquisa

Revision ID: 70335651fab2
Revises: 0cdd6dc96363
Create Date: 2024-10-14 06:43:19.942617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70335651fab2'
down_revision: Union[str, None] = '0cdd6dc96363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionarios', sa.Column('descricao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionarios', 'descricao')
    # ### end Alembic commands ###
